# Generated by Django 6.0 on 2025-12-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('Правовые акты Совета народных депутатов', 'Legal acts of the Council of People Deputies'), ('Правовые акты Администрации', 'Legal acts of the Administration'), ('Объявления', 'Ads'), ('Соглашения', 'Agreements'), ('Протокол', 'Protocol'), ('Предписания', 'Regulations')], max_length=120)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
