# Generated by Django 6.0 on 2025-12-23 17:03

import django.db.models.deletion
import file.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description1', models.TextField(choices=[('Совет народных депутатов', 'Совет народных депутатов'), ('Администрация Новоусманского муниципального района', 'Администрация Новоусманского муниципального района'), ('Контрольно-счетная палата Новоусманского муниципального района', 'Контрольно-счетная палата Новоусманского муниципального района'), ('Иные документы', 'Иные документы')], verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Типы документов',
                'verbose_name_plural': 'Типы Документов',
            },
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('uploaded_at', models.DateField(verbose_name='Дата загрузки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='FileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=file.models.upload_to, verbose_name='Файл')),
                ('context', models.CharField(verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('format', models.CharField(blank=True, max_length=20, verbose_name='Формат')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='file.filemodel', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
