# Generated by Django 6.0 on 2025-12-23 18:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Ссылка на которой менять . Пример about')),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Страницa',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
